In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import pickle
import re
from pymongo import MongoClient
from collections import defaultdict
from nltk.corpus import wordnet as wn
import nltk
from nltk import word_tokenize
from nltk.util import ngrams as ngrams_creator
from nltk.tokenize import word_tokenize
from string import punctuation 
from nltk.corpus import stopwords 
import pickle
nltk.download('vader_lexicon')
from nltk.corpus import sentiwordnet as swn
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


/usr/local/lib/python3.7/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
with open(r"drive/My Drive/NLP/processed_english_word_cluster_0-3000.pkl", "rb") as input_file:
    data1 = pickle.load(input_file)
data1

In [ ]:
with open(r"drive/My Drive/NLP/processed_english_word_cluster_3000-8000.pkl", "rb") as input_file:
    data2 = pickle.load(input_file)
# data2=data1.append(data2)
# data2.reset_index()
# data2

In [ ]:
with open(r"drive/My Drive/NLP/processed_english_word_cluster_8000-18000.pkl", "rb") as input_file:
    data3 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/processed_english_word_cluster_18000-28000.pkl", "rb") as input_file:
    data4 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/28-38/processed_english_word_cluster_28000-30000.pkl", "rb") as input_file:
    data5 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/28-38/processed_english_word_cluster_30000-34000.pkl", "rb") as input_file:
    data6 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/28-38/processed_english_word_cluster_34000-38000.pkl", "rb") as input_file:
    data7 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/processed_english_word_cluster_38000-48000.pkl", "rb") as input_file:
    data8 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/processed_english_word_cluster_48000-58000.pkl", "rb") as input_file:
    data9 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/zzzprocessed_english_word_cluster_58000-68000.pkl", "rb") as input_file:
    data10 = pickle.load(input_file)

with open(r"drive/My Drive/NLP/processed_english_word_cluster_68000-78000.pkl", "rb") as input_file:
    data13 = pickle.load(input_file)
# data3=data3.append(data2)
# daea

In [ ]:
data = pd.concat([data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data13], ignore_index=True, sort=False)
print(len(data1),len(data2),len(data3),len(data4),len(data5),len(data5),len(data6),len(data7),len(data8))
len(data)

data1[len(data1)-1:]

245 399 796 793 150 150 309 323 798


sentence_mixed  ... sentiment
244   northerncomd ia adgpi pib india spokespersonm...  ...  positive

[1 rows x 3 columns]

In [ ]:
data2.head()

sentence_mixed  ... sentiment
0   restudwibagja ridwankamil keseringan turun di...  ...   neutral
1   nimtrends kehne matra se bench ko sthagit kar...  ...   neutral
2   sarmads00529534 ye asal mein naye khiyalat ha...  ...  negative
3  8uobotjda9 hat s off you paaji tajinderbagga b...  ...  positive
4   me playing yoosung s route he s such a cinnam...  ...   neutral

[5 rows x 3 columns]

In [ ]:
data1.head()

sentence_mixed  ... sentiment
0  nen á vist bolest vztek smutek zmatek osam ě l...  ...   neutral
1   nehantics haan yaar neha 😔😔 kab karega woh po...  ...   neutral
2   rahulgandhi television media congress ke liye...  ...  negative
3   amitshah narendramodi all india me nrc lagu k...  ...  positive
4   nehr who typomantri anjanaomkashyap pagal hai...  ...   neutral

[5 rows x 3 columns]

In [ ]:
data3.head()

sentence_mixed  ... sentiment
0                                   t co 0tixqx05kw   ...   neutral
1          meghanavirat maa bhale happy ga undhi URL  ...   neutral
2   aneeza96 qasimpasha15 jawadahmadone nahi aisa...  ...  negative
3  pjxu0hjzwu rt anshuch79716462 bhakto ko naa do...  ...  positive
4  … southernnaiad marthathezealot aw it ’ s cute...  ...   neutral

[5 rows x 3 columns]

In [ ]:
with open(r"drive/My Drive/NLP/dev/processed_english_word_cluster_0-10000.pkl", "rb") as input_file:
    data = pickle.load(input_file)

len(data)    

781

In [ ]:
train_path = "/content/drive/MyDrive/NLP/hindi-english/train_14k_split_no_sw.csv"
test_path = "/content/drive/MyDrive/NLP/hindi-english/val_3k_split_no_sw.csv"
df_train = pd.read_csv(train_path)
df_val = pd.read_csv(train_path)

In [ ]:
# trainX = df_train['sentence']
trainY = df_train["sentiment"]

In [ ]:
data = df_train[["sentence","sentiment"]]
data

sentence sentiment
0      nen á vist bolest vztek smutek zmatek osam ě l...   neutral
1      Haan yaar neha pensive pensive kab karega woh ...   neutral
2      television media congress ke liye nhi h Ye toh...  negative
3      All India nrc lagu kare w Kashmir se dhara 370...  positive
4      Pagal hai kya They real issues Mandir importan...   neutral
...                                                  ...       ...
13960  Saale Gaandu khud porn dikhta hai aur dusre ko...  negative
13961  could n't get one cover birthday im going open...  positive
13962  Aap logo ki baat nahi kar raha Najim bhai Medi...  positive
13963  Jay Jay Shree Ram ram rajye aaya danavo raksha...  positive
13964  Mujhe bhayankar ho gaya hai slightly smiling f...   neutral

[13965 rows x 2 columns]

##**preprocess**


In [ ]:

def handle_short_forms(w):
    if w == 'h':
        return 'hai'
    elif w == 'n':
        return 'na'
    elif w == 'da':
        return 'the'
    elif w == 'wid':
        return 'with'
    elif w == 'pr':
        return 'par'
    elif w == 'mattt':
        return 'mat'
    elif w == 'vo':
        return 'woh'
    elif w == 'ki':
        return 'kee'
    elif w == 'ap':
        return 'aap'
    elif w == 'bs':
        return 'bas'
    elif w == 'goood':
        return 'very good'
    elif w == 'tera':
        return 'teraa'
    elif w == 'cnfsn':
        return 'confusion'
    elif w == 'ka':
        return 'kaa'
    elif w == 'rkhi':
        return 'rakhi'
    elif w == 'thts':
        return 'thats'
    elif w == 'cald':
        return 'called'
    elif w == 'tabhe':
        return 'tabhi'
    elif w == 'pta':
        return 'pata'
    elif w == 'b':
        return 'bhi'
    elif w == 'nai':
        return 'nahi'
    elif w == 'f':
        return 'of'
    elif w == 'd':
        return 'the'
    else:
        return w
    
'''
Translate word . 
'''
def translate(word):
    return translator.translate(word,src='hi' , dest='en').text

'''
Self defined contractions
''' 
def load_dict_contractions():
    
    return {
        "ain't":"is not",
        "amn't":"am not",
        "aren't":"are not",
        "can't":"cannot",
        "'cause":"because",
        "couldn't":"could not",
        "couldn't've":"could not have",
        "could've":"could have",
        "daren't":"dare not",
        "daresn't":"dare not",
        "dasn't":"dare not",
        "didn't":"did not",
        "doesn't":"does not",
        "don't":"do not",
        "e'er":"ever",
        "em":"them",
        "everyone's":"everyone is",
        "finna":"fixing to",
        "gimme":"give me",
        "gonna":"going to",
        "gon't":"go not",
        "gotta":"got to",
        "hadn't":"had not",
        "hasn't":"has not",
        "haven't":"have not",
        "he'd":"he would",
        "he'll":"he will",
        "he's":"he is",
        "he've":"he have",
        "how'd":"how would",
        "how'll":"how will",
        "how're":"how are",
        "how's":"how is",
        "I'd":"I would",
        "I'll":"I will",
        "i'll":"I will",
        "I'm":"I am",
        "I'm'a":"I am about to",
        "I'm'o":"I am going to",
        "isn't":"is not",
        "it'd":"it would",
        "it'll":"it will",
        "it's":"it is",
        "I've":"I have",
        "kinda":"kind of",
        "let's":"let us",
        "mayn't":"may not",
        "may've":"may have",
        "mightn't":"might not",
        "might've":"might have",
        "mustn't":"must not",
        "mustn't've":"must not have",
        "must've":"must have",
        "needn't":"need not",
        "ne'er":"never",
        "o'":"of",
        "o'er":"over",
        "ol'":"old",
        "oughtn't":"ought not",
        "shalln't":"shall not",
        "shan't":"shall not",
        "she'd":"she would",
        "she'll":"she will",
        "she's":"she is",
        "shouldn't":"should not",
        "shouldn't've":"should not have",
        "should've":"should have",
        "somebody's":"somebody is",
        "someone's":"someone is",
        "something's":"something is",
        "that'd":"that would",
        "that'll":"that will",
        "that're":"that are",
        "that's":"that is",
        "there'd":"there would",
        "there'll":"there will",
        "there're":"there are",
        "there's":"there is",
        "these're":"these are",
        "they'd":"they would",
        "they'll":"they will",
        "they're":"they are",
        "they've":"they have",
        "this's":"this is",
        "those're":"those are",
        "'tis":"it is",
        "'twas":"it was",
        "wanna":"want to",
        "wasn't":"was not",
        "we'd":"we would",
        "we'd've":"we would have",
        "we'll":"we will",
        "we're":"we are",
        "weren't":"were not",
        "we've":"we have",
        "what'd":"what did",
        "what'll":"what will",
        "what're":"what are",
        "what's":"what is",
        "what've":"what have",
        "when's":"when is",
        "where'd":"where did",
        "where're":"where are",
        "where's":"where is",
        "where've":"where have",
        "which's":"which is",
        "who'd":"who would",
        "who'd've":"who would have",
        "who'll":"who will",
        "who're":"who are",
        "who's":"who is",
        "who've":"who have",
        "why'd":"why did",
        "why're":"why are",
        "why's":"why is",
        "won't":"will not",
        "wouldn't":"would not",
        "would've":"would have",
        "y'all":"you all",
        "you'd":"you would",
        "you'll":"you will",
        "you're":"you are",
        "you've":"you have",
        "Whatcha":"What are you",
        "whatcha":"What are you",
        "luv":"love",
        "sux":"sucks"
        }

'''
Handling short forms and contractions in the sentences 
'''
long_form_dict = load_dict_contractions()
def expand_sent(sentence):
    final_sent =""
    res = " ".join(long_form_dict.get(ele, ele) for ele in sentence.split()) 
    for word in res.split():
        final_sent += (handle_short_forms(word))+ " "
    return final_sent

##work

In [ ]:
data.shape

(6211, 3)

In [ ]:
l=[]
for sent in data.sentence_eng:
  l.append(expand_sent(sent))

print(l[2:5])

['rahulgandhi television media congress not for you have to know this it would be good that congress ke … URL ', 'amitshah narendramodi all india me nurse lagu w kashmir dhara 370ko finish, we expect you to indian ', 'nehr who typomantri what is anjanogya ? they aren ’ t real issues mandir is important hindu which is in danger ']


##Slang word Processing



In [ ]:
slang_list = pd.read_csv("drive/My Drive/NLP/Hinglish_Profanity_List.csv",sep=",",header=None,encoding= 'unicode_escape')
slang_list.columns=['hindi_word','meaning','rating']

In [ ]:
slang_list

In [ ]:
def find_slang(sentence):
    slang_exists = False
    total_rating = 0
    for word in sentence.split():
        if not slang_list[slang_list['hindi_word']==word].empty:
            try:
                total_rating += slang_list.iloc[slang_list.index[slang_list['hindi_word'] == word].tolist()[0]]['rating']
            except:
                total_rating +=0
            slang_exists = True
    try:
        total_rating = int(total_rating)
    except:
        total_rating = 0
    return slang_exists,total_rating

In [ ]:
data['slang_exists']= data['sentence_mixed'].apply(find_slang)

In [ ]:
data[['slang_existance', 'slang_rating']] = pd.DataFrame(data['slang_exists'].tolist(), index=data.index) 
data =data.drop(columns=['slang_exists'])

In [ ]:
data

sentence_mixed  ... slang_rating
0     nen á vist bolest vztek smutek zmatek osam ě l...  ...            0
1      nehantics haan yaar neha 😔😔 kab karega woh po...  ...            0
2      rahulgandhi television media congress ke liye...  ...            0
3      amitshah narendramodi all india me nrc lagu k...  ...            0
4      nehr who typomantri anjanaomkashyap pagal hai...  ...            0
...                                                 ...  ...          ...
6206  digiye abki bar jalsa or sandar bahut bahut su...  ...            0
6207   sardanarohit kutte ke krege bhole talve aadmi...  ...            2
6208   theskindoctor13 moronhumor wish you a very ve...  ...            0
6209  ye uncle ne kya dress code kee policy padi hai...  ...           19
6210      iske bure din khatam hi nahi hota bechara URL  ...            0

[6211 rows x 5 columns]

In [ ]:
for i,j,k in zip(data['slang_existance'],data['sentence_eng'],data['slang_rating']):
  if(i==True):
    print(j,"    ",k)

##Emoji Sentiment Analysis


In [ ]:
emoji_list = pd.read_csv('drive/My Drive/NLP/Emoji_Sentiment_Data.csv',sep=",")

In [ ]:
emoji_list

Emoji  ...                          Unicode block
0       😂  ...                              Emoticons
1       ❤  ...                               Dingbats
2       ♥  ...                  Miscellaneous Symbols
3       😍  ...                              Emoticons
4       😭  ...                              Emoticons
..    ...  ...                                    ...
964     ➛  ...                               Dingbats
965     ♝  ...                  Miscellaneous Symbols
966     ❋  ...                               Dingbats
967     ✆  ...                               Dingbats
968     📔  ...  Miscellaneous Symbols and Pictographs

[969 rows x 9 columns]

In [ ]:
def find_emoji(sentence):
    positive = 0
    negative = 0
    neutral  = 0
    sentiment =[]
    for word in sentence.split():
        if not emoji_list[emoji_list['Emoji']==word].empty:
            positive += emoji_list.iloc[emoji_list.index[emoji_list['Emoji'] == word].tolist()[0]]['Positive']
            negative += emoji_list.iloc[emoji_list.index[emoji_list['Emoji'] == word].tolist()[0]]['Negative']
            neutral += emoji_list.iloc[emoji_list.index[emoji_list['Emoji'] == word].tolist()[0]]['Neutral']
    return positive,negative,neutral


In [ ]:
data['emoji_sentiment'] = data['sentence_mixed'].apply(find_emoji)

In [ ]:
data[['positive_emoji', 'negative_emoji','neutral_emoji']] = pd.DataFrame(data['emoji_sentiment'].tolist(), index=data.index) 

In [ ]:
data =data.drop(columns=['emoji_sentiment'])

In [ ]:
data.tail(50)

sentence_mixed  ... neutral_emoji
6161         itstacoos happy birthday g stay up mane 💯   ...           202
6162  💯 aajtak kumarvikrants 5 yr jrurat hi kya hai ...  ...           202
6163  vqcfrrejy9 log etna kuon gir jaata hain keh po...  ...             0
6164   arvindkejriwal things you do are not likable ...  ...             0
6165  cnayzpzujy very nice too good agar aap ahe hai...  ...             0
6166  iss paglet supriyasingh316 ne appeal kee hai t...  ...             0
6167   chitraaum mubarak ho ab aapki bhi tasweer jud...  ...          4163
6168   aabhas24 aabhas bhai iski haalat thakur jaisi...  ...             0
6169   sakhtdil krati nhi re 😨 but mast acting krta ...  ...            73
6170   kunalkamra88 abhisar sharma swamy39 par aapke...  ...             0
6171  har har modi ghra ghar modi again modiji naren...  ...             0
6172  what the fuck is this ? is chote say bachay ko...  ...             0
6173   tatapower ddl ca no060011340068 this is my ca...  ...             0
6174   jitupatwari tumhari yahi samasya hai pahle bh...  ...             0
6175  vrfzc92juw rt mohammadmna1 garmygirl sabirshak...  ...             0
6176   singhritesh09 bada na 2015 me khud ke bal pe ...  ...             0
6177   nidhinimitt reallyswara narendramodi mai bhi ...  ...             0
6178  rt phanerookampala further study daniel 124 lu...  ...             0
6179  … hardikpatel vaiya ji mann kee shanti k liye ...  ...             0
6180  mi4swinbc0 rt its atiffff bc jaga jaga zaleel ...  ...             0
6181   🙄… klishtakara yeh kya tha phir ? hate ko con...  ...             0
6182   ptshrikant sir election khatm hote hi gorakhp...  ...             0
6183   an oops04 atram shatram achee quality kaa dio...  ...             0
6184   hayahz i think the acju is providing this ser...  ...             0
6185   mamataofficial hi mam you are great c m kuch ...  ...             0
6186   majorpoonia mamataofficial sir aap rehne do h...  ...             0
6187   usambkenya hehehe may god strike them togethe...  ...             0
6188   aayeshaaw oye aisha kazmi shahkar sunoo chand...  ...             0
6189  ???🙄🤨 bsesdelhi aage mar gye ya jinda ho bses ...  ...             0
6190  i think that is the best feature of my free se...  ...             0
6191   junaidaziz007 bheer me gumne walon ko talash ...  ...             0
6192  je86z2ayha rt fishbowel guys the 🗿 emoji is so...  ...            42
6193  … indiatoday itsmunish ankit tyagi01 phle aise...  ...             0
6194  ko ban ke dena chaye jo aag me ghee dalne kaa ...  ...             0
6195   mamttaofficial ye v chal rha ispe v likha ja ...  ...             0
6196  jo achcha bolta hai kahin uske dil mai insaniy...  ...             0
6197  mai kafir kiso ko bolta hi nahi na mainay abta...  ...             0
6198   iamthedrifter change apne naam kee hi laaj ra...  ...             0
6199   sirjadeja pehly tum jaise desh bhagt choutiye...  ...             0
6200  ??🤣😂😎 donnabrazile i guess your right russia i...  ...             0
6201   udaykotak narendramodi congratulations to our...  ...             0
6202  7jqftk5hd1 rt being yogesh93 salman khan in ka...  ...             0
6203   httweets india ko khola kar diya hamaare chut...  ...             0
6204   yojphadnis happy birthday to one gem from ano...  ...             0
6205   beastboyshub bahi me apka bahut bara fan hun ...  ...             0
6206  digiye abki bar jalsa or sandar bahut bahut su...  ...             0
6207   sardanarohit kutte ke krege bhole talve aadmi...  ...             0
6208   theskindoctor13 moronhumor wish you a very ve...  ...             0
6209  ye uncle ne kya dress code kee policy padi hai...  ...            82
6210      iske bure din khatam hi nahi hota bechara URL  ...             0

[50 rows x 8 columns]

##Calculating the intensity of sentiment in a sentence using NLTK

In [ ]:
sid=SentimentIntensityAnalyzer()
neg_score=[]
pos_score=[]
neu_score=[]
for sent in data.sentence_eng:
  ss = sid.polarity_scores(sent)
  neg_score.append(ss['neg'])
  pos_score.append(ss['pos'])
  neu_score.append(ss['neu'])


In [ ]:
neg_score

[0.133,
 0.0,
 0.0,
 0.0,
 0.16,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.114,
 0.0,
 0.0,
 0.0,
 0.22,
 0.187,
 0.333,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.376,
 0.0,
 0.167,
 0.326,
 0.151,
 0.0,
 0.0,
 0.156,
 0.104,
 0.129,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.385,
 0.0,
 0.0,
 0.0,
 0.0,
 0.38,
 0.0,
 0.272,
 0.132,
 0.0,
 0.0,
 0.163,
 0.119,
 0.0,
 0.104,
 0.179,
 0.0,
 0.0,
 0.131,
 0.0,
 0.167,
 0.148,
 0.16,
 0.0,
 0.0,
 0.144,
 0.0,
 0.0,
 0.0,
 0.0,
 0.22,
 0.0,
 0.25,
 0.299,
 0.0,
 0.0,
 0.0,
 0.171,
 0.0,
 0.115,
 0.0,
 0.0,
 0.0,
 0.0,
 0.078,
 0.245,
 0.192,
 0.0,
 0.0,
 0.105,
 0.0,
 0.0,
 0.14,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.146,
 0.116,
 0.16,
 0.0,
 0.0,
 0.0,
 0.242,
 0.0,
 0.0,
 0.0,
 0.305,
 0.0,
 0.178,
 0.0,
 0.189,
 0.0,
 0.114,
 0.0,
 0.221,
 0.0,
 0.134,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.082,
 0.476,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.191,
 0.0,
 0.0,
 0.0,
 0.225,
 0.0,
 0.0,
 0.0,
 0.115,
 0.0,
 0.0,
 0.141,
 0.364,
 0

In [ ]:
data['neg_score']= neg_score
data['pos_score']= pos_score
data['neu_score']= neu_score

In [ ]:
data.tail(10)

sentence_mixed  ... neu_score
6201   udaykotak narendramodi congratulations to our...  ...     0.822
6202  7jqftk5hd1 rt being yogesh93 salman khan in ka...  ...     0.814
6203   httweets india ko khola kar diya hamaare chut...  ...     0.838
6204   yojphadnis happy birthday to one gem from ano...  ...     0.524
6205   beastboyshub bahi me apka bahut bara fan hun ...  ...     0.651
6206  digiye abki bar jalsa or sandar bahut bahut su...  ...     0.609
6207   sardanarohit kutte ke krege bhole talve aadmi...  ...     0.804
6208   theskindoctor13 moronhumor wish you a very ve...  ...     0.568
6209  ye uncle ne kya dress code kee policy padi hai...  ...     0.825
6210      iske bure din khatam hi nahi hota bechara URL  ...     0.501

[10 rows x 11 columns]

##data Prep

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [ ]:
# removing unwanted patterns from the data
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# Dividing training the test dataset

train = data[:5000]
test = data[5000:]
train

sentence_mixed  ... neu_score
0     nen á vist bolest vztek smutek zmatek osam ě l...  ...     0.867
1      nehantics haan yaar neha 😔😔 kab karega woh po...  ...     0.863
2      rahulgandhi television media congress ke liye...  ...     0.861
3      amitshah narendramodi all india me nrc lagu k...  ...     1.000
4      nehr who typomantri anjanaomkashyap pagal hai...  ...     0.755
...                                                 ...  ...       ...
4995  rt ollie dee i hope next time thesamas will sh...  ...     0.764
4996  … zi gah no not at all ye to buhat hi kum he u...  ...     0.690
4997   narendramodi namaskar to our dear honorable p...  ...     0.418
4998  eqb5iovo2m rt mohitsaini7915 dssagainstdowry g...  ...     0.759
4999  … moneybloke thand rakkho this too is not goin...  ...     1.000

[5000 rows x 11 columns]

In [ ]:
##fetching the sentence/comments from the training dataset and cleaning it

train_corpus = []

for i in range(0, 5000):
  review = re.sub('[^a-zA-Z]', ' ', train['sentence_eng'][i])
  review = review.lower()
  review = review.split()
  
  ps = PorterStemmer()
  
  # stemming
  review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  
  # joining them back with space
  review = ' '.join(review)
  train_corpus.append(review)

In [ ]:
##fetching the sentence/comments from the test dataset and cleaning it
test_corpus = []

for i in range(5000, len(data)):
  review = re.sub('[^a-zA-Z]', ' ', test['sentence_eng'][i])
  review = review.lower()
  review = review.split()
  
  ps = PorterStemmer()
  
  # stemming
  review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  
  # joining them back with space
  review = ' '.join(review)
  test_corpus.append(review)

In [ ]:
#Conversion of snetiment into numerical sentiment

train =train.replace("positive",1)
train =train.replace("negative",2)
train = train.replace("neutral",0)

In [ ]:
train_corpus

['nen vist bolest vztek smutek zmatek osam lost beznad j nakonec jen klid asi takhl vypad j life',
 'nahant ye yar neha post realli photoshoot post url',
 'rahulgandhi televis media congress know would good congress ke url',
 'amitshah narendramodi india nurs lagu w kashmir dhara ko finish expect indian',
 'nehr typomantri anjanogya real issu mandir import hindu danger',
 'lot auspici wish victori narendra modi modi ji hope peopl countri special made bihar jant url',
 'fakeionist understand plichapel hat babu kee tau new job get holiday',
 'till date sy asim waqar chitraaum syedzafarbjp ye modi media peopl also enjoy debat hindu muslim',
 'tarekfatah baih goal se therealpcb chutiy let even indian hai url',
 'desimarthastew hehe saw come actual someon marriag',
 'ecisveep answer miscalcul vote seat one vote matter countri dhji url',
 'mahaali allah pak dil dil door sb k lyhe sinc realiz prayer keep heart aajzi',
 'ravibkumarabadi cingress taken decis hope countri parti url',
 'rt mastan

In [ ]:
train.head()

sentence_mixed  ... neu_score
0  nen á vist bolest vztek smutek zmatek osam ě l...  ...     0.867
1   nehantics haan yaar neha 😔😔 kab karega woh po...  ...     0.863
2   rahulgandhi television media congress ke liye...  ...     0.861
3   amitshah narendramodi all india me nrc lagu k...  ...     1.000
4   nehr who typomantri anjanaomkashyap pagal hai...  ...     0.755

[5 rows x 11 columns]

In [ ]:
'''
bag of words for the training data
'''

bag_of_words_vectorizer = CountVectorizer(max_features=1000)
X = bag_of_words_vectorizer.fit_transform(train_corpus)
words_counts = X.toarray()
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(words_counts)

y = train.iloc[:, 2]
print(y)

0       0
1       0
2       2
3       1
4       0
       ..
4995    1
4996    2
4997    2
4998    1
4999    2
Name: sentiment, Length: 5000, dtype: int64


In [ ]:
'''
numerical features
'''
numerical_features_t = train[['neg_score','pos_score', 'neu_score', 'positive_emoji', 'negative_emoji', 'neutral_emoji', 'slang_rating']]
print(numerical_features_t.values.tolist())

[[0.133, 0.0, 0.867, 0.0, 0.0, 0.0, 0.0], [0.0, 0.137, 0.863, 1896.0, 2412.0, 1218.0, 0.0], [0.0, 0.139, 0.861, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.16, 0.085, 0.755, 0.0, 0.0, 0.0, 0.0], [0.0, 0.17, 0.83, 0.0, 0.0, 0.0, 0.0], [0.0, 0.191, 0.809, 0.0, 0.0, 0.0, 0.0], [0.0, 0.158, 0.842, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 10.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.055, 0.945, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.301, 0.699, 0.0, 0.0, 0.0, 0.0], [0.114, 0.338, 0.548, 6361.0, 355.0, 1334.0, 0.0], [0.0, 0.195, 0.805, 0.0, 0.0, 0.0, 0.0], [0.0, 0.133, 0.867, 0.0, 0.0, 0.0, 0.0], [0.0, 0.192, 0.808, 0.0, 0.0, 0.0, 0.0], [0.22, 0.146, 0.634, 0.0, 0.0, 0.0, 5.0], [0.187, 0.224, 0.588, 0.0, 0.0, 0.0, 0.0], [0.333, 0.0, 0.667, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.178, 0.822, 4640.0, 329.0, 1390.0, 0.0], [0.0, 0.204, 0.796, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 8.0], [0.0, 0.0

In [ ]:
'''
Stacking numerical features along with textual features
'''

bag_of_words_vectorizer.get_feature_names()
combinedFeatures = np.hstack([numerical_features_t, tfidf.toarray()])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
'''
using TDidf on bag f words
'''

bag_of_words_vectorizer_test = CountVectorizer(max_features=1000)
X_test = bag_of_words_vectorizer_test.fit_transform(test_corpus)
words_counts_test = X_test.toarray()
tfidf_transformer_test = TfidfTransformer()
tfidf_test = tfidf_transformer_test.fit_transform(words_counts_test)

numerical_features_test = test[['neg_score','pos_score', 'neu_score', 'positive_emoji', 'negative_emoji', 'neutral_emoji', 'slang_rating']]
print(numerical_features_test.values.tolist())

[[0.162, 0.207, 0.631, 0.0, 0.0, 0.0, 0.0], [0.158, 0.0, 0.842, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.124, 0.0, 0.876, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.102, 0.26, 0.638, 0.0, 0.0, 0.0, 0.0], [0.0, 0.188, 0.812, 0.0, 0.0, 0.0, 0.0], [0.135, 0.489, 0.376, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.385, 0.615, 0.0, 0.0, 0.0, 0.0], [0.0, 0.609, 0.391, 0.0, 0.0, 0.0, 0.0], [0.113, 0.376, 0.511, 6550.0, 437.0, 1898.0, 0.0], [0.0, 0.0, 1.0, 1910.0, 108.0, 508.0, 0.0], [0.0, 0.412, 0.588, 0.0, 0.0, 0.0, 0.0], [0.112, 0.0, 0.888, 0.0, 0.0, 0.0, 0.0], [0.101, 0.15, 0.749, 0.0, 0.0, 0.0, 20.0], [0.063, 0.303, 0.634, 0.0, 0.0, 0.0, 0.0], [0.0, 0.917, 0.083, 0.0, 0.0, 0.0, 0.0], [0.0, 0.276, 0.724, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.231, 0.0, 0.769, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.163, 0.837, 0

In [ ]:
'''
Stacking numerical features along with textual features
'''

bag_of_words_vectorizer_test.get_feature_names()
combinedFeatures_test = np.hstack([numerical_features_test, tfidf_test.toarray()])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn.model_selection import train_test_split
'''
Train test split
'''
x_train, x_valid, y_train, y_valid = train_test_split(combinedFeatures, y, random_state = 42)

print(x_train.shape)
print(x_valid.shape)
print(y_train.shape)
print(y_valid.shape)
print(combinedFeatures_test.shape)

(3750, 1007)
(1250, 1007)
(3750,)
(1250,)
(1211, 1007)


In [ ]:
# standardization

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_valid = sc.transform(x_valid)
x_test = sc.transform(combinedFeatures_test)

In [ ]:
x_valid

array([[ 0.63798074, -0.91907493,  0.48817686, ..., -0.04466374,
        -0.03849853, -0.04848335],
       [-0.62095178,  0.94086436, -0.51933946, ..., -0.04466374,
        -0.03849853, -0.04848335],
       [-0.62095178,  1.86766004, -1.40546827, ..., -0.04466374,
        -0.03849853, -0.04848335],
       ...,
       [-0.62095178,  0.61712066, -0.20980131, ..., -0.04466374,
        -0.03849853, -0.04848335],
       [ 1.49048624, -0.91907493, -0.03378943, ..., -0.04466374,
        -0.03849853, -0.04848335],
       [ 0.37033367,  0.31876863, -0.53147821, ..., -0.04466374,
        -0.03849853, -0.04848335]])

In [ ]:
'''
SVM Classifier
'''

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

model = SVC()
model.fit(x_train, y_train)

y_pred = model.predict(x_valid)

print("Training Accuracy :", model.score(x_train, y_train))
print("Validation Accuracy :", model.score(x_valid, y_valid))

# calculating the f1 score for the validation set
print("f1 score :", f1_score(y_valid, y_pred,average='macro'))

Training Accuracy : 0.8528
Validation Accuracy : 0.348
f1 score : 0.2941954524846961


In [ ]:
x_valid

In [ ]:
'''
Logistic Regression Model
'''

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_valid)

print("Training Accuracy :", model.score(x_train, y_train))
print("Validation Accuracy :", model.score(x_valid, y_valid))

# calculating the f1 score for the validation set
print("f1 score :", f1_score(y_valid, y_pred,average='macro'))

# confusion matrix
cm = confusion_matrix(y_valid, y_pred)
print(cm)

Training Accuracy : 0.6458666666666667
Validation Accuracy : 0.3384
f1 score : 0.3294027765059384
[[209 140 144]
 [176 112 123]
 [132 112 102]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
'''
Decision Tree Classifier
'''

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)

y_pred = model.predict(x_valid)

print("Training Accuracy :", model.score(x_train, y_train))
print("Validation Accuracy :", model.score(x_valid, y_valid))

# calculating the f1 score for the validation set
print("f1 score :", f1_score(y_valid, y_pred,average='macro'))

# confusion matrix
cm = confusion_matrix(y_valid, y_pred)
print(cm)

Training Accuracy : 0.9957333333333334
Validation Accuracy : 0.336
f1 score : 0.324162547293251
[[214 150 129]
 [160 121 130]
 [147 114  85]]
